name: Live Proxy Updater

on:
  schedule:
    - cron: '0 * * * *'  # Menjadwalkan workflow untuk berjalan setiap 1 jam
  workflow_dispatch:

jobs:
  run-bun:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: run generate-statistics.ts
        run: |
          cd .github/scripts
          bun run generate-statistics.ts

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Push changes
        run: |
          git add .
          git commit -m "🤖 docs: Statistics updated"
          git push
